### ISSUE TITLE
Node.js is not Build in JS

### ISSUE THREAD

**Issue by TheTokeneer** [learn-co-curriculum/js-and-the-web#4]
I think needs update on the first JS section on the part:

Various tools and libraries are built in Javascript like:

React, Ember and Angular
NodeJS
React Native - library for building iOS and Android phone apps.
D3 a charts animation library

NodeJS is build in C++ not JS.

**Comment by rrcobb** [comment]
I agree with the sentiment here, but this lesson doesn't mention NodeJS. Closing for now - if you reopen on the lesson with the error, I'd be happy to merge a fix.
