### ISSUE TITLE
Ordered list not displaying as intended

### ISSUE THREAD

**Issue by samdtall** [learn-co-curriculum/js-and-the-web#5]
Check lines 56 to 72. It's clearly intended to be 3 ordered list items with unordered sub-items, but instead it creates 6 ordered list items.
![screen shot 2018-08-07 at 7 49 49 pm](https://user-images.githubusercontent.com/17744952/43808450-13490210-9a7b-11e8-8cb3-aa6e9c51e293.png)

**Comment by rrcobb** [comment]
This should be fixed - github and learn parse markdown slightly differently, so there are some cases where the lesson will appear correct in the github interface but display wrong in learn (or vice versa).
