### ISSUE TITLE
Reporting an issue

### ISSUE THREAD

**Issue by arthuryyun** [learn-co-curriculum/js-and-the-web#6]
To Github,

https://learn.co/tracks/bootcamp-prep/javascript-fundamentals/javascript-basics/js-and-the-web.
Alice is not showing up for me. I want to debug this, but I'm not sure how I can dissect the code.

Sincerely,
A beginner

**Comment by kkterai** [comment]
This occurred for another student today who was working from a work PC. She also was unable to see Alice.

**Comment by Donnadieu** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
